# Acces aux pages de base
/:
    controller: Home
    action: default

/home:
    controller: Home
    action: default

#Inscription newsletter
/home/mail:
    controller: Home
    action: email

#Panel admin

/admin:
    controller: Admin 
    action: default

/admin/:
    controller: Admin 
    action: default

/admin/user-list:
    controller: Admin
    action: listUser

/admin/add-category:
    controller: Admin
    action: addCategory

/admin/new-category:
    controller: Category 
    action: add

/admin/add-product:
    controller: Admin
    action: addProduct

/admin/new-product:
    controller: Product 
    action: add

/admin/delete-product:
    controller: Admin
    action: deleteProduct

# Action liés à l'utilisateur
/login:
    controller: User
    action: login

/logout:
    controller: User
    action: logout

/register:
    controller: Home
    action: register

/suscribe:
    controller: User
    action: register

/confirmation:
    controller: User
    action: registerConfirm

/forgot-password:
    controller: User
    action: forgotPassword

/reset-password:
    controller: User
    action: newPassword

/profile:
    controller: User
    action: default

/shop:
    controller: Shop
    action: default

/lost:
    controller: Errors
    action: lost
